// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCED9raLQx_d5D4B3q8SDTH2JkJ4MCp_vQ',
    appId: '1:633812235853:web:96a44e61366635bede4e04',
    messagingSenderId: '633812235853',
    projectId: 'idea-chat-app-8fe6a',
    authDomain: 'idea-chat-app-8fe6a.firebaseapp.com',
    storageBucket: 'idea-chat-app-8fe6a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClFPKzhc55yhSGDMNyJlMInBfvD1K0LFU',
    appId: '1:633812235853:android:f0eb004afb35e303de4e04',
    messagingSenderId: '633812235853',
    projectId: 'idea-chat-app-8fe6a',
    storageBucket: 'idea-chat-app-8fe6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIDDCkEHoPA3QBsUBhjR0Rv9CTccJO8Vc',
    appId: '1:633812235853:ios:1c86a261446b6205de4e04',
    messagingSenderId: '633812235853',
    projectId: 'idea-chat-app-8fe6a',
    storageBucket: 'idea-chat-app-8fe6a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIDDCkEHoPA3QBsUBhjR0Rv9CTccJO8Vc',
    appId: '1:633812235853:ios:1c86a261446b6205de4e04',
    messagingSenderId: '633812235853',
    projectId: 'idea-chat-app-8fe6a',
    storageBucket: 'idea-chat-app-8fe6a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCED9raLQx_d5D4B3q8SDTH2JkJ4MCp_vQ',
    appId: '1:633812235853:web:6fa4c01665f07767de4e04',
    messagingSenderId: '633812235853',
    projectId: 'idea-chat-app-8fe6a',
    authDomain: 'idea-chat-app-8fe6a.firebaseapp.com',
    storageBucket: 'idea-chat-app-8fe6a.appspot.com',
  );
}
